### ISSUE TITLE
translations for layout form's options not being fetched

### ISSUE THREAD

**Issue by lsmod** [Xtraball/Siberian416#13]
Hi,

a while ago I described this issue:
https://github.com/Xtraball/SiberianCMS/issues/307

as I explained I found a workaround calling by Core_Model_Translator::prepare from the layout form class and finally got layout's options from translated.

Since 4.14.X this workaround doesn't work no more

**Comment by userdevel** [comment]
Maybe resolved in 4.15.x...

**Comment by Slicit** [comment]
Fixed in 4.15.11 with the completely new translation core.
