### ISSUE TITLE
ReadMe Banner Design

### ISSUE THREAD

**Issue by debpedrano** [Xtraball/Siberian416#14]
Since you have a logo , how about we will put it as a banner for ReadMe ? so it will be more attractive and pleasing to the eyes.

**Comment by Slicit** [comment]
Can you explain with some illustrations? thanks.

**Comment by debpedrano** [comment]
The banner can easily catch attention, not because it is big but because it has a cleaner look with the main project title. And you have the right choice to pick orange and blue , it is a great combination. I do hope you like it.

![image](https://user-images.githubusercontent.com/40510200/42329448-49134a82-80a3-11e8-8c55-60888b913442.png)

**Comment by debpedrano** [comment]
or this one ?

![siberian](https://user-images.githubusercontent.com/40510200/42381332-4b929ef0-8163-11e8-8291-2f0770f986f4.png)

**Comment by Slicit** [comment]
Thanks for the banners ;)
