### ISSUE TITLE
php versions greater than 7.0 marked as too old

### ISSUE THREAD

**Issue by GiddyNaya** [Xtraball/Siberian416#15]
Installations are prevented on servers with an updated php version greater than 7.0. I tried installing it on my CentOS 7 with pre-configured PHP version 7.2.5 and couldn't pass the first phase of installation because i was prompted that my version is too old whereas it's even more recent.
![screenshot_1](https://user-images.githubusercontent.com/16220887/44298963-edc2a600-a2e4-11e8-8096-61c36d6e03d5.png)

**Comment by userdevel** [comment]
Can you create a ticket here: https://github.com/Xtraball/SiberianCMS/issues?

It is important to have PHP 7.2.x and 7.3.x full compatibility too!

**Comment by Slicit** [comment]
EOL doesn't meet it will not work anymore, moreover Siberian is actually based on an old ZF1 framework, and will probably never be compatible with php 7.2

--

**Comment by userdevel** [comment]
- ZF1 EOL since 2016-09-28 (2 years): https://framework.zend.com/blog/2016-06-28-zf1-eol.html
- https://github.com/zendframework/zf1

Look for have PHP 7.2 comptability :)
- https://discourse.zendframework.com/t/php-7-and-zend-framework-1-12/327
- https://github.com/zendframework/zf1/pull/518
- https://travis-ci.org/zendframework/zf1/builds/144486314
- https://github.com/zendframework/zf1/issues?q=is%3Aopen+is%3Aissue+label%3Aphp7
- https://discourse.zendframework.com/t/zf1-community-maintained-official-fork/419
- https://github.com/zendframework/zf1/pull/748
- https://github.com/zf1s
- https://community.magento.com/t5/Magento-DevBlog/From-PHP-7-0-to-PHP-7-2-in-Magento-2-3/ba-p/91371
- https://github.com/magento/zf1
- https://stackoverflow.com/questions/35500872/which-version-of-zend-framework-1-is-compatible-with-php7
- https://packagist.org/packages/shardj/zendframework1-php7.2
- https://github.com/magento-engcom/zf1-php-7.2-support

**Comment by Slicit** [comment]
It's not "important" lot of hosting providers still use 5.6 and 7.0 is just being the next most used, just think LTS our clients have their own servers, they can't just change their php version every 6 months, and we just can't follow the requirements to update all code to make it work with all these versions

**Comment by userdevel** [comment]
I think that it is possible to update Zend 1.12.3 to 1.12.20 in first time for security point and improvements :)
- https://github.com/Xtraball/Siberian/blob/master/siberian/lib/Zend/Version.php

Source: https://github.com/zendframework/zf1/releases

**Comment by Slicit** [comment]
We did an unsuccessful upgrade to latest zf 1.12.20 in the past, our stack is highly custom and we decided to only take the updated parts. so basically we're not in 1.12.3 but in a mixed released.

**Comment by Neustradamus** [comment]
Thanks to @userdevel: Now it is easy to update, I have found all modified (and added) files from 1.12.3: https://github.com/zendframework/zf1/releases/tag/release-1.12.3

```
Siberian\Zend\Controller\Request\Http.php
Siberian\Zend\Controller\Front.php

Siberian\Zend\Db\Table\Abstract.php

+
Siberian\Zend\Feed\Reader\Extension\Media
Siberian\Zend\Feed\Reader\Extension\Picasa

Siberian\Zend\Feed\Reader\Extension\Podcast\Entry.php

Siberian\Zend\Form\Element\Email.php
Siberian\Zend\Form\Element\Submit.php
Siberian\Zend\Form\Element.php

Siberian\Zend\Locale\Data\ar_SA.xml

+
Siberian\Zend\Locale\Data\en_KE.xml
Siberian\Zend\Locale\Data\en_KY.xml
Siberian\Zend\Locale\Data\en_PG.xml
Siberian\Zend\Locale\Data\en_ZM.xml
Siberian\Zend\Locale\Data\fr_PF.xml

Siberian\Zend\Locale\Data\hi.xml

+
Siberian\Zend\Locale\Data\mfe.xml
Siberian\Zend\Locale\Data\mfe_MU.xml
Siberian\Zend\Locale\Data\nl_SR.xml
Siberian\Zend\Locale\Data\pt_MR.xml

Siberian\Zend\Locale\Data\root.xml
Siberian\Zend\Locale\Data\si.xml
Siberian\Zend\Locale\Data\sr.xml

Siberian\Zend\Locale\Format.php

+
Siberian\Zend\Pdf\Resource\Font\Simple\Standard\DejaVuSans-Bold.ttf
Siberian\Zend\Pdf\Resource\Font\Simple\Standard\DejaVuSans.ttf

Siberian\Zend\Pdf\Font.php

Siberian\Zend\Queue\Adapter\Db\postgresql.sql
Siberian\Zend\Queue\Adapter\Db\sqlsrv.sql

+ in the folder from zf1-release-1.12.3\resources (no changes)
Siberian\Zend\resources

Siberian\Zend\Rest\Server.php

Siberian\Zend\Service\Audioscrobbler.php
Siberian\Zend\Service\Technorati.php

+
Siberian\Zend\Session\SaveHandler\Redis.php

Siberian\Zend\Validate\Hostname.php
Siberian\Zend\Validate\StringLength.php

+
Siberian\Zend\View\Helper\FormEmail.php

Siberian\Zend\View\Abstract.php

Siberian\Zend\XmlRpc\Client.php

Siberian\Zend\Loader.php
Siberian\Zend\Locale.php
Siberian\Zend\Mail.php
Siberian\Zend\Session.php
```

**Comment by Neustradamus** [comment]
Important news:
- PHP 7.3.0: http://php.net/
- Debian 10 "Buster" will have PHP 7.3.0: https://wiki.debian.org/PHP

**Comment by ranjbar2446** [comment]
Do you have a plan to upgrade project's Zend Framework?

**Comment by Slicit** [comment]
ZF will not be update to any 2 or 3, but as it's our own fork, we will make it compatible with php up to 7.3 at some point yes.

**Comment by Neustradamus** [comment]
http://php.net/supported-versions.php
- PHP 5.6.40 is the last version.
- PHP 7.0.33 is the last version.
- PHP 7.3+ is recommended (Debian 10)

Linked to: https://github.com/Xtraball/SiberianCMS/issues/608

**Comment by Slicit** [comment]
As per the roadmap, partial support for php 7.1, 7.2 & 7.3 will be added soon

https://www.siberiancms.com/community/d/745-roadmap-4-15-4-16

**Comment by userdevel** [comment]
Linked to:
- https://github.com/Xtraball/SiberianCMS/issues/593
- https://github.com/Xtraball/SiberianCMS/issues/608

@SiberianCMS @dbyzero @Slicit @LikoV2: But on the roadmap, I have not seen easy opened bugs (1 year ago):
- https://github.com/Xtraball/SiberianCMS/issues/created_by/userdevel
