### ISSUE TITLE
folder v2

### ISSUE THREAD

**Issue by ghost** [Xtraball/Siberian416#19]
Hi,

Since I updated to MAE 4.15.5 yesterday I have an issue in the apps when folder v2 should load the pages and/or categories. Insteat a spinners continues forever. I already commented all .htaccess files to see if they causes the problem, but the problem still excists.

Anyone a clue wre to find this?

Kind regards,

Wouter Simons

**Comment by Slicit** [comment]
Please try again in 4.15.11 and let me know if the issue is still present
