### ISSUE TITLE
development server

### ISSUE THREAD

**Issue by ghost** [Xtraball/Siberian416#23]
Hello there and thanks for this awesome project!
I just wanted to say for those who does not have a linux and just want to see and play with Siberian , is it possible to run Siberian as a node development server?
for instance clone into code and run something like this:
`npm run start`
thanks in advance.

**Comment by Slicit** [comment]
No, you need Apache/PHP or Nginx/PHP-FPM
There is way too much dependencies, npm standalone server can't handle all of it.
