### ISSUE TITLE
Double slash in the path

### ISSUE THREAD

**Issue by sl45sms** [Xtraball/Siberian416#24]
This line has Double slash in the path of plugman.
https://github.com/Xtraball/Siberian/blob/86fcef11e7276a58bc6db4356858d4a5a0b6181c/bin/src/install.js#L15

**Comment by userdevel** [comment]
Any news for this ticket?
The "//" ?

**Comment by Slicit** [comment]
Merge request already applied.

**Comment by userdevel** [comment]
Like I have said before, double slash always here at this time (2019-05-28):
- https://github.com/Xtraball/Siberian416/blob/master/bin/src/install.js#L15
