### ISSUE TITLE
Siberian system won't generate Android source files (it just states "Generating").

### ISSUE THREAD

**Issue by bearkrust** [Xtraball/Siberian416#9]
Hi.

When I selected to button to generate the source files, all i get is "generating" and nothing happens. I close out the program and reopen and it still says "generating." I come back days later, literally, and after powering up my computer again, reopen Siberian and login and the it still states, "generating". Here it is in the Siberian editor backend:

![screenshot-2018-3-26 publish your app](https://user-images.githubusercontent.com/4074536/37938404-45346d12-3123-11e8-8f9c-8cff53069fbf.png)

And, when I go to Siberian backoffice backend,  it states "Generating", too, for the Android version. I already know that as a SAE user I have to manually compile the app using Android Studio, but I can't even do that because I need the source files, which the system won't generate when selecting the button. So, since there is a way to manually compile the app using Android Studio, **is there, too, a way to _manually generate the source files_ and for the Android version?**

Thanks.

**Comment by AnthonyLELUYER** [comment]
Hi @bearkrust,

You either have to set up the cron scheduler (https://doc.siberiancms.com/knowledge-base/how-to-set-the-cron-scheduler/) or disable it on your Backoffice > Settings > Advanced > Cron.

If you choose to disable it, you also have to clean your database, delete all rows in the table "source_queue", and try to generate the sources again.
